server.port=8081
# Configuration de Camel
camel.servlet.mapping.context-path=/api/*

# Swagger UI servi via webjars a : /webjars/swagger-ui/index.html?url=/api/api-doc

# Static resources location for Angular app
spring.web.resources.static-locations=classpath:/static/browser/

logging.level.org.dbs.poc.unblu=DEBUG
unblu.api.summary-bot-person-id=tkbR8LA7Sm2J6-eSliAsFg

# Mock configuration
mock.rule-engine.enabled=true
mock.rule-engine.default-team-id=cAaYUeKyTZ25_OaA6jUeVA