server.port=8081
camel.servlet.mapping.context-path=/api/*

# Configuration de Swagger UI (Springdoc)
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
logging.level.org.dbs.poc.unblu=DEBUG
unblu.api.summary-bot-person-id=tkbR8LA7Sm2J6-eSliAsFg