server:
  port: 8082

spring:
  application:
    name: livekit
  dotenv:
    enabled: true


unblu:
  api:
    base-url: ${UNBLU_API_BASE_URL:https://services8.unblu.com/app/rest/v4}
    username: ${UNBLU_API_USERNAME}
    password: ${UNBLU_API_PASSWORD}
  bot:
    named-area-id: ${UNBLU_BOT_NAMED_AREA_ID:}

logging:
  level:
    org.dbs.poc.unblu: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html

resilience4j:
  circuitbreaker:
    instances:
      unblu:
        registerHealthIndicator: true
        slidingWindowSize: 20
        failureRateThreshold: 50
  retry:
    instances:
      unblu:
        maxAttempts: 3
        waitDuration: 2000
