spring:
  application:
    name: unblu


unblu:
  api:
    base-url: ${UNBLU_API_BASE_URL:https://services8.unblu.com/app/rest/v4}
    username: ${UNBLU_API_USERNAME}
    password: ${UNBLU_API_PASSWORD}
    bot-name: ${UNBLU_BOT_NAME:Boby}
    proxy:
      host: ${UNBLU_PROXY_HOST:}
      port: ${UNBLU_PROXY_PORT:8080}
      username: ${UNBLU_PROXY_USERNAME:}
      password: ${UNBLU_PROXY_PASSWORD:}
