server.port=8081
camel.servlet.mapping.context-path=/api/*

# Configuration de Swagger UI (Springdoc)
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Dit à Springdoc de venir lire la définition générée par Camel
springdoc.swagger-ui.url=/api/openapi.json
